# Configurazione Rosso di Sera Blog
title: "Rosso di Sera"
tagline: "Una luce nel mondo digitale"
description: "Blog di riflessioni, cultura e tecnologia. Esploriamo insieme il mondo digitale con uno sguardo critico e appassionato."
url: "https://rossodiserablog.pages.dev"
baseurl: ""

# Author principale (per SEO)
author:
  name: "Lino Rialti & StE2808"
  email: "s.vozzi@gmail.com"
  twitter: "@rossodiserablog"

# Logo per Schema.org
logo: "/assets/images/logo_trasparenza.png"

# Social profiles
social:
  name: "Rosso di Sera"
  links:
    - https://github.com/StE2808/rossodiserablog

# Impostazioni SEO
lang: it_IT
timezone: Europe/Rome

# Autori
collections:
  authors:
    output: true

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Paginazione
paginate: 12
paginate_path: "/pagina/:num/"

# Plugin
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Feed RSS
feed:
  path: feed.xml
  excerpt_only: true

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      sitemap: true
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"

# Esclusioni
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
